version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - .env
    networks:
      - transcendance
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./src/frontend/react:/app
      - /app/node_modules
    env_file:
      - .env
    restart: on-failure
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "5555:5555"
    volumes:
      - ./src/backend/nest:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - transcendance
    restart: always
volumes:
  postgres_data:
networks:
  transcendance: