# Étape de construction
FROM node:21 as build
WORKDIR /app
COPY ./react/package.json ./react/package-lock.json ./
RUN npm install
COPY ./react/ .
RUN npm run build

# Étape de production
FROM nginx:alpine

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
